name: Flutter iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.1'  # Updated to latest stable as of 2025; adjust if needed

    - name: Install dependencies
      run: flutter pub get

    - name: Decode certificate
      run: |
        echo "${{ secrets.IOS_CERTIFICATE }}" | base64 --decode > certificate.p12
        ls -l certificate.p12  # Diagnostic: Check file size

    - name: Decode provisioning profile
      run: |
        echo "${{ secrets.PROVISIONING_PROFILE }}" | base64 --decode > profile.mobileprovision
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
        ls -l profile.mobileprovision  # Diagnostic: Check file size

    - name: Setup keychain
      run: |
        security create-keychain -p pwd build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p pwd build.keychain

    - name: Import certificate
      run: |
        security import certificate.p12 -k build.keychain -P "${{ secrets.P12_PASSWORD }}" -T /usr/bin/codesign || echo "Import failed - check secret values"
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k pwd build.keychain
        security find-identity -v -p codesigning  # Diagnostic: List identities to verify import

    - name: Build IPA
      run: |
        flutter build ipa --release --export-method ad-hoc --bundle-version 1.0.0 --bundle-short-version-string 1.0 --provisioning-profile-uuid 0b68e1cd-eff0-4306-a2c4-878008e53bcb

    - name: Archive artifact
      uses: actions/upload-artifact@v4
      with:
        name: first-ios-app-ipa
        path: build/ios/ipa/*.ipa
