name: Flutter iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List Xcode versions
      run: ls -l /Applications | grep Xcode

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.1'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: List available iOS runtimes
      run: xcrun simctl list runtimes

    - name: Build iOS with xcodebuild
      run: |
        cd ios
        xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release -sdk iphoneos -destination 'generic/platform=iOS' CODE_SIGNING_ALLOWED=NO
      env:
        DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

    - name: Archive artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: ios/build/Release-iphoneos/Runner.app