name: Re-Sign and Upload IPA to App Store

on:
  workflow_dispatch:  # Manual trigger since you have the .ipa

jobs:
  resign-and-upload:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Decode certificate
      run: |
        echo "${{ secrets.IOS_CERTIFICATE_APPSTORE }}" | base64 --decode > appstore.p12
        ls -l appstore.p12

    - name: Decode provisioning profile
      run: |
        echo "${{ secrets.PROVISIONING_PROFILE_APPSTORE }}" | base64 --decode > appstore.mobileprovision
        ls -l appstore.mobileprovision
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp appstore.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

    - name: Setup keychain
      run: |
        security create-keychain -p pwd build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p pwd build.keychain
        security import appstore.p12 -k build.keychain -P "${{ secrets.P12_PASSWORD }}" -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k pwd build.keychain
        security find-identity -v -p codesigning

    - name: Download IPA artifact
      uses: actions/download-artifact@v4
      with:
        name: first-ios-app-ipa  # Adjust if different
        path: ./ipa

    - name: Re-sign IPA
      run: |
        unzip ./ipa/Runner.ipa -d ./extracted  # Extract .ipa
        rm -rf ./extracted/Payload/Runner.app/_CodeSignature  # Remove old signature
        cp appstore.mobileprovision ./extracted/Payload/Runner.app/embedded.mobileprovision  # Embed new profile
        codesign -f -s "Apple Distribution: Preston (D296S46TFC)" ./extracted/Payload/Runner.app  # Re-sign with your certificate identity
        zip -r Runner-appstore.ipa ./extracted/Payload  # Re-package .ipa

    - name: Upload to App Store Connect
      run: |
        xcrun altool --upload-app -f Runner-appstore.ipa -u "${{ secrets.APPLE_ID }}" -p "${{ secrets.APP_SPECIFIC_PASSWORD }}"  # Use your Apple ID and app-specific password

    - name: Archive re-signed IPA
      uses: actions/upload-artifact@v4
      with:
        name: re-signed-ipa
        path: Runner-appstore.ipa
