name: Flutter iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Build iOS
      run: |
        flutter build ios --release --no-codesign
      env:
        DEVELOPER_DIR: /Applications/Xcode_15.4.app/Contents/Developer

    - name: Archive artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: build/ios/iphoneos/*.app